
CREATE TABLE IF NOT EXISTS exercises (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  photo_url VARCHAR(255) NULL,
  reps_schema VARCHAR(255) NULL,
  day_of_week TINYINT UNSIGNED NOT NULL,
  suggested_weight DECIMAL(8,2) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_day_name (day_of_week, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  exercise_id BIGINT UNSIGNED NOT NULL,
  performed_at DATETIME NOT NULL,
  set_index SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  weight DECIMAL(8,2) NULL,
  reps SMALLINT UNSIGNED NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_exercise_performed (exercise_id, performed_at),
  CONSTRAINT fk_logs_ex FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
